version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
